//! AetherProof — cryptographic AI execution receipt engine.
//!
//! Author: Pulkit Kr Srivastava <pulkitsrivastavae@gmail.com>
//!
//! Generates, signs, verifies, and serialises 128-byte Ed25519-signed receipts
//! that satisfy EU AI Act 2025 §13(3)(c) technical documentation requirements
//! for automated decision-making systems.
//!
//! # Wire format (128 bytes, little-endian)
//! ```text
//! [0..8]    magic         "AETHPRF1"
//! [8]       version       1
//! [9..12]   _pad          [0; 3]
//! [12..16]  pid           u32
//! [16..24]  binary_hash   u64  FNV-1a of model/binary bytes
//! [24..32]  memory_hash   u64  hash of inference outputs (or 0)
//! [32..36]  syscall_count u32  number of calls / inference steps
//! [36..40]  entropy_seed  u32  random nonce at generation
//! [40..48]  timestamp_ns  u64  nanoseconds since Unix epoch
//! [48..56]  binary_len    u64  byte count of model/binary
//! [56..64]  _reserved     [0; 8]
//! [64..128] sig           [u8; 64]  Ed25519 over bytes[0..64]
//! ```
//!
//! The wire format is identical to the AetherOS kernel receipt format —
//! receipts generated by the kernel can be verified by this library and CLI.

pub mod pq;

use ed25519_dalek::{Signature, Signer, Verifier};
pub use ed25519_dalek::{SigningKey, VerifyingKey};

// ── Constants ──────────────────────────────────────────────────────────────────

pub const RECEIPT_MAGIC:   [u8; 8] = *b"AETHPRF1";
pub const RECEIPT_VERSION: u8      = 1;
pub const RECEIPT_SIZE:    usize   = 128;
/// Bytes of the serialised receipt covered by the signature (everything before
/// the signature field itself).
pub const SIGNED_PREFIX:   usize   = 64;

/// Dev signing seed — matches AetherOS kernel `DEV_SIGNING_SEED`.
/// Replace with HSM/TPM-derived key in production.
pub const DEV_SIGNING_SEED: [u8; 32] = [
    0x4a, 0xe3, 0x81, 0xb9, 0x2f, 0x6c, 0x05, 0xd8,
    0x17, 0xa4, 0x9e, 0x63, 0x2b, 0x78, 0xf1, 0x5c,
    0x9d, 0x02, 0xe7, 0x48, 0xbc, 0x6a, 0x31, 0x94,
    0x5f, 0xc8, 0x7e, 0xab, 0x03, 0xd5, 0x6f, 0x22,
];

// ── Receipt struct ─────────────────────────────────────────────────────────────

/// A single AI execution receipt.
#[derive(Debug, Clone, PartialEq)]
pub struct Receipt {
    pub pid:           u32,
    /// FNV-1a hash of the model/binary bytes.
    pub binary_hash:   u64,
    /// Hash of model outputs or AI-owned memory region. 0 if not tracked.
    pub memory_hash:   u64,
    /// Number of inference calls or syscalls the run made.
    pub syscall_count: u32,
    /// Random nonce sampled at generation time.
    pub entropy_seed:  u32,
    /// Nanoseconds since Unix epoch at generation time.
    pub timestamp_ns:  u64,
    /// Byte count of the model/binary.
    pub binary_len:    u64,
    /// Ed25519 signature over bytes[0..64] of the serialised receipt.
    pub sig:           [u8; 64],
}

// ── Hash primitive ─────────────────────────────────────────────────────────────

/// FNV-1a 64-bit hash — identical to the kernel's implementation.
pub fn fnv1a(data: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for &b in data {
        h ^= b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

// ── Time + entropy ─────────────────────────────────────────────────────────────

fn now_ns() -> u64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_nanos() as u64)
        .unwrap_or(0)
}

fn entropy_u32() -> u32 {
    let mut buf = [0u8; 4];
    getrandom::getrandom(&mut buf).unwrap_or(());
    u32::from_le_bytes(buf)
}

// ── Core API ───────────────────────────────────────────────────────────────────

/// Generate and sign a receipt for one AI inference run.
///
/// `binary`        — the model or binary bytes being audited
/// `memory_hash`   — hash of model outputs (use `fnv1a(output_bytes)` or 0)
/// `syscall_count` — number of inference calls / operations
/// `signing_key`   — Ed25519 signing key (use `dev_signing_key()` in dev)
pub fn generate(
    pid:           u32,
    binary:        &[u8],
    memory_hash:   u64,
    syscall_count: u32,
    signing_key:   &SigningKey,
) -> Receipt {
    let mut r = Receipt {
        pid,
        binary_hash:   fnv1a(binary),
        memory_hash,
        syscall_count,
        entropy_seed:  entropy_u32(),
        timestamp_ns:  now_ns(),
        binary_len:    binary.len() as u64,
        sig:           [0u8; 64],
    };
    // Sign the first 64 bytes of the serialised receipt (sig field is zero during signing).
    let serialised = to_bytes(&r);
    r.sig.copy_from_slice(&signing_key.sign(&serialised[0..64]).to_bytes());
    r
}

/// Serialise a receipt to 128 bytes (little-endian).
pub fn to_bytes(r: &Receipt) -> [u8; RECEIPT_SIZE] {
    let mut out = [0u8; RECEIPT_SIZE];
    out[0..8].copy_from_slice(&RECEIPT_MAGIC);
    out[8]        = RECEIPT_VERSION;
    // [9..12] padding stays zero
    out[12..16].copy_from_slice(&r.pid.to_le_bytes());
    out[16..24].copy_from_slice(&r.binary_hash.to_le_bytes());
    out[24..32].copy_from_slice(&r.memory_hash.to_le_bytes());
    out[32..36].copy_from_slice(&r.syscall_count.to_le_bytes());
    out[36..40].copy_from_slice(&r.entropy_seed.to_le_bytes());
    out[40..48].copy_from_slice(&r.timestamp_ns.to_le_bytes());
    out[48..56].copy_from_slice(&r.binary_len.to_le_bytes());
    // [56..64] reserved stays zero
    out[64..128].copy_from_slice(&r.sig);
    out
}

/// Deserialise 128 bytes into a Receipt. Returns `None` on magic/version mismatch.
pub fn from_bytes(data: &[u8; RECEIPT_SIZE]) -> Option<Receipt> {
    if data[0..8] != RECEIPT_MAGIC   { return None; }
    if data[8]    != RECEIPT_VERSION { return None; }
    let mut sig = [0u8; 64];
    sig.copy_from_slice(&data[64..128]);
    Some(Receipt {
        pid:           u32::from_le_bytes(data[12..16].try_into().ok()?),
        binary_hash:   u64::from_le_bytes(data[16..24].try_into().ok()?),
        memory_hash:   u64::from_le_bytes(data[24..32].try_into().ok()?),
        syscall_count: u32::from_le_bytes(data[32..36].try_into().ok()?),
        entropy_seed:  u32::from_le_bytes(data[36..40].try_into().ok()?),
        timestamp_ns:  u64::from_le_bytes(data[40..48].try_into().ok()?),
        binary_len:    u64::from_le_bytes(data[48..56].try_into().ok()?),
        sig,
    })
}

/// Verify the Ed25519 signature over bytes[0..64] of a 128-byte receipt.
pub fn verify(data: &[u8; RECEIPT_SIZE], vk: &VerifyingKey) -> bool {
    if data[0..8] != RECEIPT_MAGIC { return false; }
    let sig = match Signature::from_slice(&data[64..128]) {
        Ok(s)  => s,
        Err(_) => return false,
    };
    vk.verify(&data[0..64], &sig).is_ok()
}

/// Tamper probe: proves receipts are tamper-evident.
///
/// Flips a byte inside `binary_hash` field, checks → INVALID.
/// Then verifies original → VALID.
/// Returns `true` iff both hold.
pub fn tamper_probe(original: &[u8; RECEIPT_SIZE], vk: &VerifyingKey) -> bool {
    let mut tampered = *original;
    tampered[20] ^= 0xFF;
    !verify(&tampered, vk) && verify(original, vk)
}

/// Return the dev signing key from `DEV_SIGNING_SEED`.
pub fn dev_signing_key() -> SigningKey {
    SigningKey::from_bytes(&DEV_SIGNING_SEED)
}

/// Return the dev verifying key (public half of `DEV_SIGNING_SEED`).
pub fn dev_verifying_key() -> VerifyingKey {
    VerifyingKey::from(&dev_signing_key())
}

// ── Tests ──────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn sk() -> SigningKey      { dev_signing_key() }
    fn vk() -> VerifyingKey    { dev_verifying_key() }

    // ── Format invariants ──────────────────────────────────────────────────────

    #[test]
    fn receipt_size_is_128() {
        assert_eq!(RECEIPT_SIZE, 128, "wire format frozen at 128 bytes");
    }

    #[test]
    fn magic_field_correct() {
        let r = generate(1, b"test", 0, 0, &sk());
        let b = to_bytes(&r);
        assert_eq!(&b[0..8], b"AETHPRF1");
        assert_eq!(b[8], 1); // version
    }

    #[test]
    fn padding_and_reserved_are_zero() {
        let r = generate(1, b"model", 0, 0, &sk());
        let b = to_bytes(&r);
        assert_eq!(&b[9..12],  &[0u8; 3],  "pad bytes must be zero");
        assert_eq!(&b[56..64], &[0u8; 8],  "reserved bytes must be zero");
    }

    // ── Round-trip ─────────────────────────────────────────────────────────────

    #[test]
    fn roundtrip_all_fields() {
        let r = generate(42, b"hello_world", 0xDEAD_BEEF_CAFE_0000, 7, &sk());
        let b = to_bytes(&r);
        let r2 = from_bytes(&b).expect("from_bytes must succeed on valid receipt");
        assert_eq!(r.pid,           r2.pid);
        assert_eq!(r.binary_hash,   r2.binary_hash);
        assert_eq!(r.memory_hash,   r2.memory_hash);
        assert_eq!(r.syscall_count, r2.syscall_count);
        assert_eq!(r.entropy_seed,  r2.entropy_seed);
        assert_eq!(r.timestamp_ns,  r2.timestamp_ns);
        assert_eq!(r.binary_len,    r2.binary_len);
        assert_eq!(r.sig,           r2.sig);
    }

    #[test]
    fn from_bytes_rejects_wrong_magic() {
        let r  = generate(1, b"x", 0, 0, &sk());
        let mut b = to_bytes(&r);
        b[0] = b'X';
        assert!(from_bytes(&b).is_none());
    }

    #[test]
    fn from_bytes_rejects_wrong_version() {
        let r  = generate(1, b"x", 0, 0, &sk());
        let mut b = to_bytes(&r);
        b[8] = 99;
        assert!(from_bytes(&b).is_none());
    }

    // ── Signature verification ─────────────────────────────────────────────────

    #[test]
    fn freshly_generated_receipt_is_valid() {
        let r  = generate(1, b"model.onnx", 0, 0, &sk());
        let b  = to_bytes(&r);
        assert!(verify(&b, &vk()), "generated receipt must verify");
    }

    #[test]
    fn verify_rejects_wrong_key() {
        use ed25519_dalek::SigningKey;
        let wrong_seed = [0xFFu8; 32];
        let wrong_vk   = VerifyingKey::from(&SigningKey::from_bytes(&wrong_seed));
        let r  = generate(1, b"model", 0, 0, &sk());
        let b  = to_bytes(&r);
        assert!(!verify(&b, &wrong_vk), "wrong key must not verify");
    }

    #[test]
    fn verify_rejects_wrong_magic() {
        let r  = generate(1, b"m", 0, 0, &sk());
        let mut b = to_bytes(&r);
        b[0] ^= 0x01;
        assert!(!verify(&b, &vk()));
    }

    // ── Tamper evidence ────────────────────────────────────────────────────────

    #[test]
    fn tamper_probe_passes() {
        let r = generate(1, b"model", 0, 0, &sk());
        let b = to_bytes(&r);
        assert!(tamper_probe(&b, &vk()), "tamper probe must pass");
    }

    #[test]
    fn flip_every_metadata_byte_invalidates() {
        let r = generate(99, b"stress", 0xABCD, 5, &sk());
        let orig = to_bytes(&r);
        // Flip each byte in [0..64) individually (metadata region).
        // Bytes 9..12 are padding (zero), flipping them changes the message too.
        for i in 0..64usize {
            let mut t = orig;
            t[i] ^= 0x55;
            assert!(
                !verify(&t, &vk()),
                "flipping metadata byte {i} must invalidate the receipt"
            );
        }
    }

    #[test]
    fn flip_every_sig_byte_invalidates() {
        let r = generate(1, b"m", 0, 0, &sk());
        let orig = to_bytes(&r);
        for i in 64..128usize {
            let mut t = orig;
            t[i] ^= 0xAA;
            assert!(
                !verify(&t, &vk()),
                "flipping sig byte {i} must invalidate the receipt"
            );
        }
    }

    // ── Determinism & uniqueness ───────────────────────────────────────────────

    #[test]
    fn binary_hash_is_fnv1a_of_binary() {
        let binary = b"my_model_v1.onnx";
        let r = generate(1, binary, 0, 0, &sk());
        assert_eq!(r.binary_hash, fnv1a(binary));
    }

    #[test]
    fn different_binaries_produce_different_hashes() {
        let r1 = generate(1, b"model_a", 0, 0, &sk());
        let r2 = generate(1, b"model_b", 0, 0, &sk());
        assert_ne!(r1.binary_hash, r2.binary_hash);
    }

    #[test]
    fn binary_len_is_correct() {
        let binary = b"hello_aetherproof_world";
        let r = generate(1, binary, 0, 0, &sk());
        assert_eq!(r.binary_len, binary.len() as u64);
    }

    // ── Stress (100 receipts, all verify) ─────────────────────────────────────

    #[test]
    fn stress_100_receipts_all_verify() {
        let vk = vk();
        for i in 0u32..100 {
            let binary = format!("model_iteration_{i}");
            let r = generate(i, binary.as_bytes(), i as u64, i, &sk());
            let b = to_bytes(&r);
            assert!(verify(&b, &vk), "receipt {i} must verify");
            // round-trip
            let r2 = from_bytes(&b).unwrap();
            assert_eq!(r.binary_hash, r2.binary_hash);
        }
    }

    // ── FNV-1a known vector ────────────────────────────────────────────────────

    #[test]
    fn fnv1a_empty_input() {
        // FNV-1a of empty slice is the offset basis
        assert_eq!(fnv1a(b""), 0xcbf2_9ce4_8422_2325);
    }

    #[test]
    fn fnv1a_known_vector() {
        // "foobar" FNV-1a-64 from the reference table
        assert_eq!(fnv1a(b"foobar"), 0x85944171f73967e8);
    }
}
